### ISSUE TITLE
Ampersand symbol ("&") in body of the email breaks the activity details

### ISSUE THREAD

**Issue by mecachisenros** [veda-consulting/uk.co.vedaconsulting.outlookapi#14]
Congratulations for the great work with this extension, just started testing it a while ago, and it looks amazing.

I've noticed that when using the ampersand symbol in the email body, everything seems to work as expected, the activity is created successfully in CiviCRM but when I check the activity details (ie click on View in the activity tab) the activity's details only shows the message until the ampersand symbol, anything written after the ampersand is striped out.

So for example if I put this in an email: **_This is a nice "&" ampersand character._**
In the activity details it will show only: **_This is a nice "_**

Having a look at the params when the activity is created looks like the issue is generated in Outlook? Or when the data is sent to the server?
```
[civicrm_install_type] => wordpress
    [activity_type_id] => 3
    [subject] => FW:  Ampersand \"
    [email] => my_email@gmail.com
    [email_body] => This is a nice “
    [ot_target_contact_id] => 35257
    [activity_type] => Email
    [check_permissions] => 1
    [version] => 3
```

Tested with Outlook 2013 / 2010 and CiviCRM 4.6.4/4.6.10

**Comment by mecachisenros** [comment]
Any clues on this issue?

**Comment by priyankakaran26** [comment]
Hi mecachisenros,

Thanks for pointing that out, we'll take a look and get back to you asap.

Thanks again!

**Comment by mecachisenros** [comment]
Thanks @priyankakaran26, please let me know if there's anything I can do to help.

**Comment by priyankakaran26** [comment]
Hey @mecachisenros 

We've fixed this. Please download v2.0.6 from the link below and let us know if it's working for you.
http://www.vedaconsulting.co.uk/outlookforcivicrm-civicase

Thanks

**Comment by mecachisenros** [comment]
Many thanks @priyankakaran26, I'll test it now and I'll report back.

**Comment by mecachisenros** [comment]
@priyankakaran26 I've tested it with Outlook 2010/2013, works perfectly, thank you very much.

This is off topic but, has anyone tested it with Wordpress as CMS? I can't get the _prompt for cases_ to work.

**Comment by priyankakaran26** [comment]
Hi @mecachisenros,

Good to know that it's working fine for you. OutlookForCiviCRM is independent of CMS being used, so that should not pose any problem. May be it's something to do with the permissions in Civi, could you try that?

I am closing this issue as this is resolved. 

Thanks,
Priyanka
