### ISSUE TITLE
Limit Case Activity types to only the ones enabled

### ISSUE THREAD

**Issue by mecachisenros** [veda-consulting/uk.co.vedaconsulting.outlookapi#20]
I'm testing the Case feature, the last update fixed it, it wasn't working for me on Wordpress.

I just noticed that the Activity Type drop-down for cases it shows only core case activity types (see image below), I think it would be great to have instead the activity types set/allowed in the case type settings (CiviCase-Case Types-Edit Case, in the activity types tab)

Perhaps adding something like this to the api:

```
function _civicrm_api3_civi_outlook_getallowedcaseactivitytype_spec(&$spec) {
  $spec['case_type_id']['api.required'] = 1;
}



function civicrm_api3_civi_outlook_getallowedcaseactivitytype($params) {

    $allowedActivities = civicrm_api3('CaseType', 'getsingle', array(
        'sequential' => 1,
        'id' => $params['case_type_id'],
        'return' => "definition",
    );

    $result = array();
    foreach ($allowedActivities['definition']['activityTypes'] as $value) {
        $result[] = $value['name'];
    }
    return $result;
}
```

![capture](https://cloud.githubusercontent.com/assets/3038096/17978290/28548342-6aed-11e6-9ce9-dda48ff0028e.PNG)

Any thoughts?

**Comment by priyankakaran26** [comment]
Hi @mecachisenros 

Thanks for that. We'll have a look and get back to you on this.

Regards,
Priyanka

**Comment by mecachisenros** [comment]
@priyankakaran26 I just decompiled the `OutLookForCiviCRM.dll` file to have a look at the source, now I have no idea about c# or .net but the `ConfirmActivity_Load` method in the `ConfirmActivity` class (I guess that's a class and a method) checks for whether Prompt for Case is enabled and that we are logging the activity against a Case ( `if(isCiviCase){ if (dontFileAgainstCiviCase){ ... } else{ // log against case ... } }` ).
In that else statement is where the api call is made to get the Case activity types:
```
...
// about line 833
string restData3 = common5.getRestData(string.Concat(new string[]
							{
								this.resourceURL,
								"/extern/rest.php?entity=CiviOutlook&action=getcaseactivitytype&api_key=",
								this.apikey,
								"&key=",
								this.sitekey
							}));
```
What I'm suggesting is to modify the `getcaseactivitytype` call to take `case_id` as a parameter and return the allowed activity types mentioned in my comment above something like:
```
function civicrm_api3_civi_outlook_getcaseactivitytype($params) {
    $case = civicrm_api3('Case', 'getsingle', array(
        'id' => $params['case_id'],
    ));
    $allowedActivities = civicrm_api3('CaseType', 'getsingle', array(
        'sequential' => 1,
        'id' => $case['case_type_id'],
        'return' => "definition",
    );

    $result = array();
    foreach ($allowedActivities['definition']['activityTypes'] as $value) {
        $result[] = $value['name'];
    }
    return $result;
}
```
And then in the `ConfirmActivity_Load` method pass the the case_id to the api call, something like:
```
...
// about line 833
int caseid = AddinModule.CurrentInstance.caseId;
string restData3 = common5.getRestData(string.Concat(new string[]
							{
								this.resourceURL,
								"/extern/rest.php?entity=CiviOutlook&action=getcaseactivitytype&api_key=",
								this.apikey,
								"&key=",
								this.sitekey,
								"&case_id=",
								caseid
							}));
```

Apologies for my poor explanation, hope it makes sense.

**Comment by priyankakaran26** [comment]
Hi @mecachisenros 

Yep that makes sense.  We'll implement this and let you know. :)

At the moment, we are a bit busy with the group sync functionality and would be releasing a new plugin version soon. We'll pick this up asap after that.

Thanks a lot!
Priyanka

**Comment by mecachisenros** [comment]
Hi @priyankakaran26

Thanks for considering those changes.
I would be more than happy to contribute to the project with code/testing.
Is there any chance we could get the Outlook plugin source code?
If so I could start implementing this.

**Comment by priyankakaran26** [comment]
Hi @mecachisenros 

Currently we're not in position to share the source code but we're looking to build the necessary process in the next few months.

Thanks
Priyanka

**Comment by mecachisenros** [comment]
@priyankakaran26 any updates on this?

**Comment by priyankakaran26** [comment]
Hi @mecachisenros 

We were a bit caught up with the add-on functionalities for group sync hence couldn't pick this up. But you could expect this to be in sooner than later.

Thanks

**Comment by veda-consulting** [comment]
@priyankakaran26 did we get this completed? If not can we please get onto it ASAP?

**Comment by priyankakaran26** [comment]
Hi @mecachisenros 

This is now done.
Commit -> https://github.com/veda-consulting/uk.co.vedaconsulting.outlookapi/commit/9887845743d740c28089141a4ad2a649132c4da0

Thanks for all your input. :)

Priyanka
