### ISSUE TITLE
API Permission Check failed

### ISSUE THREAD

**Issue by vmantese** [veda-consulting/uk.co.vedaconsulting.outlookapi#21]
I'm the administrator so I should have all rights but I'm getting the error:

API permission check failed for CiviOutlook/getdomain call; insufficient permisssions: require access CiviCRM and Access Ajax API.

Like i said I'm confused because I should have all rights. I have the right site key and api_key. Any ideas?

**Comment by priyankakaran26** [comment]
Hi there,

Thanks for letting us know.

Could you confirm you using the latest version of Outlook Civi extension(2.0.2) and OutlookForCiviCRM plugin(2.0.8)?
Also which CMS are you guys using?

Thanks & Regards,
Priyanka

**Comment by vmantese** [comment]
Hi Priyanka,
We are using CiviCRM 4.5.5 on Wordpress 4.5.
I am using 2.0.8 in the outlook plugin and the current git master whatever
version that is.

Please let me know what I can do to help.


Vito

**Comment by jmcheung** [comment]
hi @priyankakaran26 

We also have a similar issue with an administrator account seeing that error.
CiviCRM 4.6.19
Wordpress 4.5.4
Name (key)	CiviOutlook API (uk.co.vedaconsulting.outlookapi)
Description	Custom API to support Outlook requests
Download location	
Local path	/home/lcvsorg/public_html/wp-content/plugins/files/civicrm/extensions/uk.co.vedaconsulting.outlookapi-master
Documentation	http://www.vedaconsulting.co.uk/outlookforcivicrm-release
Licensing	http://www.gnu.org/licenses/agpl-3.0.html
Main Extension Page	http://vedaconsulting.co.uk
Support	http://vedaconsulting.co.uk
Author	Veda NFP Consulting Ltd (support@vedaconsulting.co.uk)
Version	2.0.2
Released on	2016-07-01
License	AGPL-3.0
Development stage	stable
Compatible with	4.5   4.6   4.7  

The plugin installer is OutLookForCiviCRM-v1.1.msi
Is there anything obvious we're missing or doing wrong?

Jon-man

**Comment by priyankakaran26** [comment]
Hi Jon-man (@jmcheung),

Hope you are doing good. 

Could you try this version of Outlook plugin instead http://www.vedaconsulting.co.uk/sites/default/files/veda-uploads/uploads/2016/OutlookForCiviCRM/OutlookForCiviCRM-v2.0.8.zip

Also could you update Outlook Civi extension by checking out the master branch here: https://github.com/veda-consulting/uk.co.vedaconsulting.outlookapi

Let me know how it goes.

Thanks,
Priyanka

**Comment by priyankakaran26** [comment]
Hi @vmantese 

We'll have a look and get back to you.

Thanks very much,
Priyanka

**Comment by jmcheung** [comment]
Thanks Priya! @priyankakaran26 

I'm fine thanks. Got a 7 month old now so very busy. Missed you at CiviCon London this year.

I'll update the plugin and extensions, then retry.

Jon-man

**Comment by priyankakaran26** [comment]
Wow many many congratulations Jon-man! :) @jmcheung 

Yeah couldn't make it to Civicon this year, had deadlines on multiple projects. 

Sure, give it a try and let me know!

Priyanka

**Comment by priyankakaran26** [comment]
Hi guys, @vmantese @jmcheung 

I just ran a quick test and this appears to be working fine. We also had a client report the same issue and it turned out that the api key they were using had a different Wordpress user associated with it which didn't have an admin role. The best way to double check this is to refer to "CiviCRM ID / User ID" on civi contact's screen or check civicrm_uf_match table.

If this doesn't work out for you, try installing "User Role Editor" plugin which exposes the CiviCRM permissions as well and you can tick/untick permissions as needed. Wordpress does not expose the admin capabilities/permissions unlike Drupal and so we just have to assume that admin has all the permissions.

Please give it a shot and let me know if it works.

Thanks,
Priyanka

**Comment by jmcheung** [comment]
hi @priyankakaran26 

Does it need to have a Wordpress admin role for the plugin to work?

Jon-man

**Comment by adam-devapp** [comment]
![get_domain](https://cloud.githubusercontent.com/assets/13082954/22249394/c297f8ae-e292-11e6-8311-08b7290fb86c.png)

On Drupal running latest, won't authenticate past this error get_domain
Running CiviCRM 4.7.11 and Drupal 7 (latest)

**Comment by veda-consulting** [comment]
Sounds like permissions issue?

Check that the user has a role which allows "CiviCRM: access CiviCRM"

You could test it by running the following URL in your site to ensure the
user in question has API access.

https://yoursite.com/sites/all/modules/civicrm/extern/rest.php?entity=Domain&action=get&api_key=userkey&key=sitekey&json={"sequential":1}

**Comment by adam-devapp** [comment]
The link when injected with site key and API key appears to work. Returns:
{"is_error":0,"version":3,"count":1,"id":1,"values":[{"id":"1","name":"......etc, with the domain details for the site.
Also checked Drupal permissions and have everything ticked under People -> Permissions, including access access CiviCRM. Same error unfortunately.

**Comment by veda-consulting** [comment]
@adam-devapp we have just tried the latest versions of the extension/plugin and CiviCRM and everything works as expected. I would suggest upgrading to latest CiviCRM (or setup a test vanilla system to cross check the credentials etc).

**Comment by adam-devapp** [comment]
Thanks. Yes appears to work. The web page link on the CiviCRM module points to the wrong version. I had to find 2+ in the GIT repo folders. Client also downloaded wrong one too.

http://www.vedaconsulting.co.uk/outlookforcivicrm-release  points to:
https://vedaconsulting.co.uk/outlookforcivicrm-release
which shows v1.1

Perhaps one of these pages can be updated to point to the new binary to avoid confusion.

**Comment by priyankakaran26** [comment]
@adam-devapp Thanks for trying out the extension.
We've now updated the doc on our site so should be ok now.
