### ISSUE TITLE
API Permission issue

### ISSUE THREAD

**Issue by agileware** [veda-consulting/uk.co.vedaconsulting.outlookapi#25]
Hi, Thank you very much for creating this extension to provide this feature for CiviCRM.

Encountered an issue while using this extension.

## Background:

- A role called `CiviCRM Edit` that has been assigned all the permissions that we can find in the documentation and your extension code, but not `CiviCRM: administer CiviCRM` and `CiviOutlook API: view APIkeys`
   - Permissions NOT assigned:
       - administer CiviCRM *
       - translate CiviCRM
       - administer reserved groups/reserved tags/dedpue rules
       - view debug output
       - all permissions related to manual batches
       - administer payment processors
       - edit API/own API Keys
       - delete in CiviContribute
       - administer reports/reserved reports
       - view report sql
       - CiviOutlook API: view APIkeys *
- A role called `CiviCRM admin` that has been assigned all the permissions, but just not `translate CiviCRM` and `CiviOutlook API: view APIkeys`
- All Users account that have been assigned with one of these two roles have both WP users and CiviCRM contacts record, and the relationship between them has been established.
- All User assigned with any one of these two roles have generated API key in CiviCRM using `API key Management` extension function.
- Tested User has generated API key and site key and plugin url correctly filled out in Outlook plugin Settings.

## Issue description:
(will call users that have been assigned `CiviCRM edit` role, as`edit` for short in following.)
(will call users that have been assigned `CiviCRM admin` role, as`admin` for short in following.)

1. `edit` can not get the default activity type that is set in the CiviOutlook settings, when send an email in Outlook, need to manually select activity type for them.
1.  After select activity type, it reports alert message in Outlook `Invalid Acitivity ID, this might cause attachments not being saved`. And the activity is not created in CiviCRM.
1. `Admin` can get the default activity type, but when sending a email and creating an activity in CiviCRM, outlook throw an error message `Invalid ContactID or ActivityID. Activity doesn't belong to this contact. Hence couldn't attach the files`, but the activity has been created after that.
1. After assigned `administer CiviCRM` permission to `edit`, `edit` will have the same issue with `admin` as described in 3.
1. After assigned `CiviOutlook API: view APIkeys` to `admin` or `edit` that is assigned `administer CiviCRM` permission, the error message in 3 goes away, activity created successfully.
1. If `edit` is not assigned `administer CiviCRM` but with `CiviOutlook API: view APIkeys`, it has the same problem as described in 1 and 2.

## Environment

- Both the latest version of `API Key Management` v1.2 and `CiviOutlook API` v2.1 extensions installed in CiviCRM
- CMS: WP 4.7.2
- CRM: CiviCRM 4.7.16
- Outlook: 2016
- Outlook plugin: 2.1.1

If possible, could you please have an investigation on this issue?

Again many thanks for your work.

All the best

Agileware Ref 24793

**Comment by veda-consulting** [comment]
@agileware thanks for the feedback. We've had another user report that the "administer CiviCRM" permission is required to carry out certain functions, we're looking into this ate the moment, hoping to have a resolution next week.

**Comment by agileware** [comment]
@veda-consulting How are things going with this issue, any updates? Need help?

**Comment by veda-consulting** [comment]
@agileware could you try this on the latest release and report back if your still having the same issue please? Thanks

**Comment by agileware** [comment]
Thanks again, will do.

**Comment by veda-consulting** [comment]
@agileware we're closing this assuming fixed, if its not please do let us know by re-opening
