### ISSUE TITLE
Outlook 2016 compatibility

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.outlookapi#26]
Hi. Is it known whether this works with Outlook 2016? 
We're trying it out, but get a warning message: "Invalid Activity ID" and nothing is getting saved into Civi (4.7.x).
Also, even when 'Prompt for all emails" is turned off, we're still seeing the prompt.

**Comment by priyankakaran26** [comment]
@Upperholme Hiya,

Yes it works with latest version of Outlook as well i.e 2016. Please make sure you've got the latest version of Outlook plugin and Outlook Civi extension.

Would be good to double check error messages(if any) in the Outlook log file (C:/OutlookAccessLogs/access_log.txt)

Do let us know how you get on with this.

Thanks
Priyanka

**Comment by mattwire** [comment]
We had the same issue at a client that was resolved by updating the civicrm extension to the latest version or running from master.  A new release was tagged yesterday (2.1.1), otherwise you'd be running 2.0.2 which gave us the invalid activity ID message (Outlook 2013).

**Comment by veda-consulting** [comment]
Update to this, we've just tagged a new release v2.1.5, will close this issue as no comments since March 2017
