### ISSUE TITLE
Failed to authenticate key

### ISSUE THREAD

**Issue by Czollli** [veda-consulting/uk.co.vedaconsulting.outlookapi#28]
Hi,
Wordpress 4.8, Civicrm 4.6.28, Outlookapi 2.1.1 and corresponding Outlook plugin (2.1.5) on client side.

User is able to connect to CiviCRM and verifies her account (so I assume URL, site and api key should be ok), however when at sending mail she clicks 'Yes' to record the sending of the email in CivCRM she gets the error message above.

Her Wordpress account is Administrator so all CiviCRM permission should be assigned.

Does anybody have idea what else to check?
Can the problem be Wordpress related?

Thanks

**Comment by Czollli** [comment]
C:/OutlookAccessLogs/access_log.txt tells a bit more:

07-06-2017 15:13:16: Authenticating account from Outlook, Function name - addAccount: ERROR: No CMS user associated with given api-key
07-06-2017 15:16:47: Create Activity, Function name - sendEmail: Failed to authenticate key
07-06-2017 15:18:46: Create Activity, Function name - sendEmail: Failed to authenticate key
07-06-2017 15:21:52: Create Activity, Function name - sendEmail: Failed to authenticate key
07-06-2017 15:28:57: Create Activity, Function name - sendEmail: Failed to authenticate key

However there is a user associated with correct api key.

mysql> select c.id AS Civi_id , c.display_name, m.uf_id AS WP_id, uf_name AS WP_UserName , c.api_key from civicrm_uf_match m INNER JOIN civicrm_contact c ON c.id = m.contact_id where c.api_key IS NOT NULL;;
+---------+--------------------+-------+------------------+--------------------------+
| Civi_id | display_name       | WP_id | WP_UserName      | api_key                  |
+---------+--------------------+-------+------------------+--------------------------+
|   30171 | Dr. Test User |   266 | user@test.org.uk | PiXXXXXXXXXXXXXXXXXXXXXw |
+---------+--------------------+-------+------------------+--------------------------+
1 row in set (0.00 sec)

**Comment by priyankakaran26** [comment]
Hi @Czollli 

I see, so the error ->No CMS user associated with given api-key is being returned from Civi.
So could you do the following steps and see if it works out for you?

1.  Reset API key for the admin user.
2. Disconnect and reconnect the Outlook plugin and see if you're able to connect to CiviCRM using the new API key.

Its possible that when the admin user connected to CiviCRM and verified their account, the key they used at that time was valid but later it changed for some reason?

Do try this out and let us know how you got on.

Thanks
Priyanka

**Comment by veda-consulting** [comment]
@Czollli no update since June, I'll close this on the assumption all is ok if not please do open it up again. Thanks
