### ISSUE TITLE
Releases need to be updated

### ISSUE THREAD

**Issue by agileware** [veda-consulting/uk.co.vedaconsulting.outlookapi#29]
Hi Veda,

I can see that 2.1.5 ( https://github.com/veda-consulting/uk.co.vedaconsulting.outlookapi/commit/ca15d0fcd59e5ee9930a5c6bd5fe6113349fb96d ) of this plugin is available, however the latest official release is 2.1.1 ( https://github.com/veda-consulting/uk.co.vedaconsulting.outlookapi/commit/587b7b4ae2d4b8628021b4083da482c4aeae813e )

Are you able to mark a new release to keep this up to date. Thanks in advance.

**Comment by veda-consulting** [comment]
Have pushed a new release, should hit the CiviCRM Extensions directory tonight or tomorrow.

**Comment by agileware** [comment]
Thank you !
