### ISSUE TITLE
exception thrown in outlook

### ISSUE THREAD

**Issue by eruraindil** [veda-consulting/uk.co.vedaconsulting.outlookapi#3]
Super interested in this extension, however have been having some trouble.

 * civicrm 4.5
 * outlook 2013

When I send a message, outlook throws an exception.
In civicrm the activity shows up with contact who sent the message, however the contact who is sent the message doesn't get an activity added, instead a new contact is created with a string of characters as their email and name.

I don't know enough about outlook addins to be able to properly diagnose this. It says "Cannot save attachment", but there isn't even an attachment in the email I am trying to send. Would someone be able to help?

here is the outlook exception:
==
```
Detailed technical information follows: 
---
(Inner Exception)
Date and Time:         2015-07-02 3:12:40 PM
Machine Name:          <MY COMPUTER NAME>
IP Address:            <MY IP>
Current User:          <MY USERNAME>

Application Domain:    C:\Users\<MY USERNAME>\AppData\Local\VEDA NFP Consulting Ltd\OutLookForCiviCRM\
Assembly Codebase:     file:///C:/Users/<MY USERNAME>/AppData/Local/VEDA NFP Consulting Ltd/OutLookForCiviCRM/Interop.Outlook.DLL
Assembly Full Name:    Interop.Outlook, Version=9.0.0.0, Culture=neutral, PublicKeyToken=3c8e198007f9ecf8
Assembly Version:      9.0.0.0

Exception Source:      Microsoft Outlook
Exception Type:        System.Runtime.InteropServices.COMException
Exception Message:     Cannot save the attachment. Cannot add the attachment; no data source was provided.
Exception Target Site: SaveAsFile

---- Stack Trace ----
   Outlook.Attachment.SaveAsFile(Path As String)
       Interop.Outlook.DLL: N 00000 (0x0) JIT 
   OutLookForCiviCRM.AddinModule.GetAttachmentsInfo(attached As Attachments, url As String, activityID As Int32)
       Interop.Outlook.DLL: N 0227 (0xE3) IL 
   OutLookForCiviCRM.AddinModule.sendEmail(mailTo As String, subject As String, emailBody As String, mailAttachments As Attachments, url As String, apikey As String, sitekey As String, mailItem As MailItem)
       Interop.Outlook.DLL: N 1457 (0x5B1) IL 
   OutLookForCiviCRM.AddinModule.adxOutlookEvents_ItemSend(sender As Object, e As ADXOlItemSendEventArgs)
       Interop.Outlook.DLL: N 0283 (0x11B) IL 
   AddinExpress.MSO.ADXOutlookAppEvents.DoItemSend(item As Object, cancel As Boolean&)
       Interop.Outlook.DLL: N 0026 (0x1A) IL 



(Outer Exception)
Date and Time:         2015-07-02 3:12:40 PM
Machine Name:          <MY COMPUTER NAME>
IP Address:            <MY IP>
Current User:          <MY USERNAME>

Application Domain:    C:\Users\<MY USERNAME>\AppData\Local\VEDA NFP Consulting Ltd\OutLookForCiviCRM\
Assembly Codebase:     file:///C:/Users/<MY USERNAME>/AppData/Local/VEDA NFP Consulting Ltd/OutLookForCiviCRM/AddinExpress.MSO.2005.DLL
Assembly Full Name:    AddinExpress.MSO.2005, Version=7.6.4084.2005, Culture=neutral, PublicKeyToken=4416dd98f0861965
Assembly Version:      7.6.4084.2005

Exception Source:      
Exception Type:        AddinExpress.MSO.ADXExternalException
Exception Message:     An error has occurred in the code of the add-in.
Exception Target Site: Object reference not set to an instance of an object.

---- Stack Trace ----


```

**Comment by veda-consulting** [comment]
@eruraindil Thanks for the bug report. I'm sure we can take a look. To confirm you've installed both the outlook plugin and the CiviCRM extension?

**Comment by eruraindil** [comment]
@veda-consulting yes, both are installed.

Thanks for looking into this.

**Comment by veda-consulting** [comment]
@eruraindil thanks, we've just managed to reproduce the issue. We're working on a resolution and will update when done. Thanks

**Comment by veda-consulting** [comment]
@eruraindil p.s. the issue is down to any inline images in the email. As a test you could send a plain text email and you should then see it pushed through to CiviCRM.

**Comment by priyankakaran26** [comment]
@eruraindil
Hi,
We've fixed this, could you try re-installing Outlook plugin from here: http://www.vedaconsulting.co.uk/sites/default/files/veda-uploads/uploads/2015/OutlookForCiviCRM/OutlookForCiviCRM.zip

Also please take the latest update of Outlook extension for CiviCRM.
https://github.com/veda-consulting/uk.co.vedaconsulting.outlookapi/releases/tag/v1.1

Thanks

**Comment by eruraindil** [comment]
@priyankakaran26 Thanks, I will try this tomorrow!

**Comment by eruraindil** [comment]
Thanks for fixing the issue!
