### ISSUE TITLE
Resource URL

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.outlookapi#35]
In the readme file it states that the CiviCRM resource URL needs to be entered into the outlook plugin to set it up: "Can be found on Administer >> System Settings >> Resource URLs screen in CiviCRM."
and in the image, which is Drupal-centric, I can see that it refers to http://example.com/sites/all/modules/civicrm

Assuming the same to be true for a Wordpress installation, should the URL be of the form http://example.com/path/to/plugins/civicrm/civicrm ?

**Comment by priyankakaran26** [comment]
Hi @Upperholme 

Yes that should work. It's basically to let Outlook plugin know the location of the CiviCRM directory via that url.

Thanks

**Comment by Upperholme** [comment]
Many thanks for the prompt and helpful response. 

The doc is a tad confusing as it mentions "Can be found on Administer >> System Settings >> Resource URLs screen in CiviCRM." In the install I'm working on right now this [civicrm.root], and even when I click on the ? help button it states:
"Example
If your site's home url is http://www.example.com/ ... then your CiviCRM Resource URL would be:
   http://www.example.com/" which isn't very helpful.

**Comment by priyankakaran26** [comment]
ok thanks for letting us know. We'll make a note of it and amend/update the doc/help description the next time we do a release. Cheers!
