### ISSUE TITLE
Error message in 

### ISSUE THREAD

**Issue by fanellit** [veda-consulting/uk.co.vedaconsulting.outlookapi#44]
I am trying to sync groups from CiviCRM to Outlook; however, I keep getting this error.

Please make sure you’ve got ‘Sync to Outlook’ setting ticked under group settings in Civi or there are no contacts in the group/s. Hence aborting sync.

**Comment by fanellit** [comment]
I now have a new error regarding permissions.

![image](https://user-images.githubusercontent.com/39093547/39767264-4fd2efca-52b4-11e8-8c34-c27efe26b034.png)

**Comment by veda-consulting** [comment]
@fanellit can you check your user permissions? The user who's API your using. You'll need to check they have the two permissions being reported by the plugin.

**Comment by fanellit** [comment]
Is there a limit to how many contacts or groups can be synced?



[ACHP-logo-Abbreviation.jpg]

Toni Fanelli I Senior Manager, Membership and GovernanceI Alliance of Community Health Plans
1825 Eye Street, NW, Suite 401, Washington, District of Columbia 20006
Email: tfanelli@achp.org<mailto:tfanelli@achp.org> I Ph: 202-524-7754 I www.achp.org<http://www.achp.org/>
[cid:image006.jpg@01D429B9.66CDD100]<https://twitter.com/_ACHP> [cid:image007.jpg@01D429B9.66CDD100] <https://www.linkedin.com/company/alliance-of-community-health-plans-achp->


The Alliance of Community Health Plans (ACHP) and its members improve the health of the communities we serve and actively lead the transformation of health care to promote high quality, affordable care and superior consumer experience.

**Comment by veda-consulting** [comment]
@fanellit no limits, maybe try the latest version as we've done quite a lot of work on it

**Comment by fanellit** [comment]
Still receiving the same error. I have uninstalled and reinstall newest version.



[ACHP-logo-Abbreviation.jpg]

Toni Fanelli I Senior Manager, Membership and GovernanceI Alliance of Community Health Plans
1825 Eye Street, NW, Suite 401, Washington, District of Columbia 20006
Email: tfanelli@achp.org<mailto:tfanelli@achp.org> I Ph: 202-524-7754 I www.achp.org<http://www.achp.org/>
[cid:image006.jpg@01D4F07E.1A6E9FB0]<https://twitter.com/_ACHP> [cid:image007.jpg@01D4F07E.1A6E9FB0] <https://www.linkedin.com/company/alliance-of-community-health-plans-achp->


The Alliance of Community Health Plans (ACHP) and its members improve the health of the communities we serve and actively lead the transformation of health care to promote high quality, affordable care and superior consumer experience.
