### ISSUE TITLE
Each outlook user to have its own content

### ISSUE THREAD

**Issue by rajeshrhino** [veda-consulting/uk.co.vedaconsulting.outlookapi#45]
**Current Behaviour:** The outlook plugin can be setup by providing an API key for a specific user. This user is only accepted if it has access to ALL contacts in CiviCRM. This means that all contacts from all groups that are marked as 'Sync to Outlook' are imported into the outlook contacts folder.

**Expected Behaviour:** The plugin accepts users that only have access to certain contacts and groups. The most elegant of defining the contacts would be to user CiviCRM ACL's. The outlook plugin would only fetch the contacts to which a user has been given access to though this mechanism.

**Example:**

- A CiviCRM access contact group "Assistants" is created
- A CiviCRM contact group "Assistants contacts" is created, "Sync to Outlook" is ticked for this group
- Through the ACLs, the group "Assistants" is granted access to group "Assistants contacts"
- A user is created and added to the CiviCRM group "Assistants", the option access to all contacts is disabled for that user's role
- If the API key for this user is used in the plugin, only the contacts that are in the group "Assistants contacts" are imported to Outlook

**Comment by veda-consulting** [comment]
In Release 3.0.2
