### ISSUE TITLE
does the OutlookForCiviCRM installer automatically replace older installed versions?

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.outlookapi#53]
Working with a client who's keen to use this. We tried an earlier version and it led to some issues. Now want to try 3.0.2 to see if its an improvement. Will the installer simply overwrite and previously installed version of the plugin, or is there an uninstall process to remove earlier code before installation?

**Comment by veda-consulting** [comment]
@Upperholme yes most of the time! Depends on permissions etc
