### ISSUE TITLE
Add-in express trial

### ISSUE THREAD

**Issue by adam-devapp** [veda-consulting/uk.co.vedaconsulting.outlookapi#56]
When installing the extension, the user is now prompted they have a trial version of Add-in Express when they open outlook.

![image](https://user-images.githubusercontent.com/13082954/44315212-06f06180-a461-11e8-9d4b-ae3120630d5c.png)

How can this message be suppressed, and what will happen to the extension at the end of the trial?

**Comment by veda-consulting** [comment]
@adam-devapp are you still seeing this? you shouldn't anymore
